# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'lesson23 homeWork' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for lesson23 homeWork
  
  pod 'Alamofire', '~> 5.4'
  pod 'AlamofireNetworkActivityLogger', '~> 3.4'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'RealmSwift', '~>10'
  pod 'RxSwift', '6.2.0'
  pod 'RxCocoa', '6.2.0'
#  pod 'GoogleMaps', '5.2.0'
  pod 'GoogleMaps-m1', git: 'https://github.com/khramtsoff/GoogleMaps-m1'
  pod 'Firebase/Analytics'
  pod 'Firebase/Crashlytics'
  pod 'Firebase/RemoteConfig'
end
